plugins:
   - stylelint-scss
   - stylelint-order
rules:
   at-rule-blacklist:
      - - debug
        - warn
      - severity: warning
   # Decide on a direction for block padding.
   at-rule-empty-line-before:
      - always
      - except:
           - first-nested
           - blockless-after-same-name-blockless
      - ignore:
           - after-comment
   at-rule-name-case: lower
   at-rule-name-space-after: always
   at-rule-no-vendor-prefix: true
   at-rule-semicolon-newline-after: always
   at-rule-semicolon-space-before: never
   # Decide on a direction for block padding.
   block-closing-brace-empty-line-before: never
   block-closing-brace-newline-after: always
   block-closing-brace-newline-before: always
   block-opening-brace-newline-after: always
   block-opening-brace-space-before: always
   block-no-empty: true
   color-named:
      - never
      - ignore:
           - inside-function
   color-hex-case: upper
   color-hex-length: short
   color-no-invalid-hex: true
   comment-no-empty: true
   declaration-block-no-duplicate-properties:
      - true
      - ignore:
           - consecutive-duplicates-with-different-values
   declaration-block-no-redundant-longhand-properties: true
   declaration-block-semicolon-newline-after: always
   declaration-block-semicolon-newline-before: never-multi-line
   declaration-block-semicolon-space-after: always-single-line
   declaration-block-semicolon-space-before: never
   declaration-block-trailing-semicolon: always
   declaration-block-single-line-max-declarations: 1
   # Decide on a direction for block padding.
   declaration-empty-line-before:
      - always
      - except:
           - after-comment
           - after-declaration
           - first-nested
   declaration-no-important: true
   font-family-name-quotes: always-where-recommended
   font-weight-notation: numeric
   function-calc-no-unspaced-operator: true
   function-linear-gradient-no-nonstandard-direction: true
   indentation:
      - 3
   length-zero-no-unit: true
   max-nesting-depth:
      # Change this down to 2/3 once we have a working rule for ignoring `/^&-/`
      - 7
      - ignore:
           - pseudo-classes
      - ignoreAtRules:
           - at-root
           - each
           - for
           - function
           - if
           - include
           - media
           - mixin
           - supports
           - while
   media-feature-colon-space-after: always
   media-feature-colon-space-before: never
   media-feature-name-case: lower
   media-feature-name-no-unknown: true
   media-feature-name-no-vendor-prefix: true
   media-feature-range-operator-space-after: always
   media-feature-range-operator-space-before: always
   no-duplicate-selectors: true
   no-eol-whitespace: true
   number-leading-zero: never
   number-no-trailing-zeros: true
   property-case: lower
   property-no-unknown:
      - true
      - checkPrefixed: true
   property-no-vendor-prefix: true
   # Decide on a direction for block padding.
   rule-empty-line-before:
      - always
      - except:
           - after-single-line-comment
           - first-nested
   selector-class-pattern:
      - '^[a-z][0-9a-z]+(?:-[0-9a-z]+){0,4}$'
      - severity: warning
      - resolveNestedSelectors: true
   selector-combinator-space-after: always
   selector-combinator-space-before: always
   selector-descendant-combinator-no-non-space: true
   selector-list-comma-newline-after: always
   # Increased to 3 temporarily, hopefully we can move towards decreasing this.
   selector-max-combinators: 3
   selector-max-empty-lines: 0
   selector-max-id: 0
   # Format is "id,class,type", hopefully we can move towards decreasing the class specificity
   selector-max-specificity: '0,6,1'
   selector-no-vendor-prefix: true
   selector-pseudo-class-case: lower
   selector-pseudo-class-no-unknown: true
   selector-pseudo-element-case: lower
   selector-pseudo-element-colon-notation: double
   selector-pseudo-element-no-unknown: true
   selector-type-case: lower
   selector-type-no-unknown: true
   shorthand-property-no-redundant-values: true
   string-no-newline: true
   string-quotes: single
   unit-case: lower
   unit-no-unknown: true
   value-keyword-case: lower
   value-no-vendor-prefix: true
   order/order:
      - - dollar-variables
        - type: at-rule
          name: extend
        - type: at-rule
          name: each
          hasBlock: false
        - type: at-rule
          name: include
        - declarations
        - type: at-rule
          name: include
          parameter: breakpoint
          hasBlock: true
        - type: at-rule
          name: include
          parameter: territory
          hasBlock: true
        - at-rules
        - rules
        - type: at-rule
          name: for
        - type: at-rule
          name: each
          hasBlock: true
        - type: rule
          selector: '#[{][^}]+?[}]'
      - disableFix: false
   scss/at-else-closing-brace-newline-after: always-last-in-chain
   scss/at-else-closing-brace-space-after: always-intermediate
   scss/at-else-if-parentheses-space-before: always
   scss/at-extend-no-missing-placeholder: true
   scss/at-function-parentheses-space-before: never
   scss/at-function-pattern:
      - '^[0-9a-z]+(-[0-9a-z]+)*$'
      - severity: warning
   scss/at-if-closing-brace-newline-after: always-last-in-chain
   scss/at-if-closing-brace-space-after: always-intermediate
   scss/at-mixin-parentheses-space-before: never
   scss/at-mixin-pattern:
      - '^[0-9a-z]+(-[0-9a-z]+)*$'
      - severity: warning
   scss/at-rule-no-unknown: true
   scss/dollar-variable-colon-newline-after: always-multi-line
   scss/dollar-variable-colon-space-after: always-single-line
   scss/dollar-variable-colon-space-before: never
   scss/dollar-variable-empty-line-before:
      - always
      - except:
           - after-comment
           - after-dollar-variable
           - first-nested
   scss/dollar-variable-no-missing-interpolation: true
   scss/dollar-variable-pattern:
      - '^[0-9a-z]+(-[0-9a-z]+)*$'
      - severity: warning
   scss/percent-placeholder-pattern:
      - '^[0-9a-z]+(-[0-9a-z]+)*$'
      - severity: warning
   scss/declaration-nested-properties: never
   scss/operator-no-newline-after: true
   scss/operator-no-newline-before: true
   scss/operator-no-unspaced: true
   scss/selector-nest-combinators: always
   scss/selector-no-redundant-nesting-selector: true
